### ISSUE TITLE
Example JS

### ISSUE THREAD

**Issue by rivertam** [silvermine/serverless-plugin-multiple-responses#2]
Hey there, I'm really confused about how I'd actually use this with JavaScript. Maybe I'm mistaken, but it seems like this is a way to choose a different response type depending on how the lambda function behaves.

I appreciate the example `serverless.yml`, but I don't really know how to actually select between the different responses.

Specifically, I'm trying to make something similar to a blogging platform. In the case where the entry is found, I'd like to respond with a 200 response. In the case where the entry is not found, I'd like to respond with a 404. I believe I'd need to create Responses similar to the one you have in standardResponses, but I don't understand how to choose between them in the JavaScript. I'm currently responding by just using `callback(null, rawHTML)` where `rawHTML` is an HTML string.

Could you please include the sample JavaScript that would go along with the sample `serverless.yml` provided in the README, or at least explain how to accomplish a simple task like the one I described above?

**Comment by jthomerson** [comment]
Closing older tickets. The recommended approach now is not to use this plugin, but instead to use the APIGW proxy integration so that you have full control over response headers and status codes.
