### ISSUE TITLE
Error using serverless 1.20

### ISSUE THREAD

**Issue by endymion00** [silvermine/serverless-plugin-multiple-responses#3]
I've configured a test handler in order to test the plugin but I'm getting a bunch of errors like this:
Serverless: Error: could not find CloudFormation object for testplugin:v1/users/testplugin/{user_id}
Serverless: Error: could not find CloudFormation object for getUserByIdDevelop:v1/users/{user_id}
Serverless: Error: could not find CloudFormation object for putUserProfileMe:v1/users/{user_id}/profile
Serverless: Error: could not find CloudFormation object for getUserProfileByIdAuth:v1/users/{user_id}/profile
.

However the deploy is done but I think the plugin it does not work.
Also there is a lack of documentation. It is not clear how to to use it.

Please can you help me? 
Thank you in advance

**Comment by casabian** [comment]
I stumbled over the same issue.

I was able to reproduce the issue with functions containing path variables. Cloudformation identifies path variables in the resource name with the ending 'Var' e.g. 'ApiGatewayMethodUsersUserIdVarGet'. That case is not handled properly in the plugin.

**Comment by jthomerson** [comment]
@endymion00 @casabian I no longer recommend using this plugin. Sorry that wasn't clear from the opening paragraphs of the README that say:

> Once that feature is supported in SLS this plugin will no longer be needed or maintained.

It's now pretty standard practice to use the APIGW proxy integration with new Serverless functions so that you have full control over the response code and headers. Hope that helps.
